spring:
  redis:
    database: 0
    host: ${YOMA_REDIS_HOST}
    password: ${YOMA_REDIS_PASSWORD}
    port: ${YOMA_REDIS_PORT}
    timeout: 20000ms
    lettuce:
      pool:
        #        避免本地调试的时候频繁报连接超时的错  ， 参见 https://juejin.im/post/6844903990090694663
        max-wait: 20000ms